# Blog config
keywords:
author: Niv Lab
description: A collection of publicly available<br>behavioral datasets

# icon
favicon: /images/favicon.webp
avatar: /images/logo.webp
logo_dir: /images/logo@2x.webp
logo_style: width:200px;

copyright:
  show: false
  default: ""
  show_author: true

footbar:
  copyright: MIT License
  beian:
  gongan:

# Social Links
# If you want to add more, go to sidebar.pug
github: https://github.com/nivlab/opendata
mail:
zhihu:
QQ:
twitter:
instagram:
rss:
facebook:
weibo:

# Nav menu
menu:
  Home: /opendata
  Archives: /opendata/archives
  Tags: /opendata/tags
  About: /opendata/about
  Contribute: /opendata/contribute
  # Links: /links

# Navbar rightbtn
rightbtn:
  back: true
  search: true
  avatar: true

# Some settings
useSummary: true     # enable it will use summary of your posts in index
summaryLength: 580   # maximum number of characters when abbreviating posts
useTagCloud: false   # use tagcloud instead of tag list
tocMaxDepth: 6       # if you set 0, toc will close. The maximum is 6.

# Comment
duoshuo:
disqus:
gentie:
# Valine comments https://valine.js.org
valine:
  enable: false # if you want use valine, please set enable: true
  appid:  # your leancloud appid
  appkey:  # your leancloud appkey
  notify: false # true/false:mail notify
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: hello, world # comment box placeholder

Baidutongji: false
